#!/usr/bin/env python3
"""Generate TOOLS.md and tools.json from the live MCP tool schemas.

Introspects the registered FastMCP tools (names, descriptions, input schemas)
and writes:

* ``TOOLS.md``   -- human/AI-readable reference of every tool and its arguments.
* ``tools.json`` -- machine-readable list of {name, description, arguments}.

Run from the repo root:  python scripts/gen_tools_doc.py
"""

from __future__ import annotations

import asyncio
import json
import os
import sys

# Make 'src' importable when run from the repo root without installation.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from maltego_mcp.server import mcp  # noqa: E402


def _resolve_params(schema: dict) -> tuple[dict, list]:
    """Return (properties, required) for a tool's single 'params' model.

    FastMCP wraps a single Pydantic argument named 'params'; resolve the $ref to
    the model definition in $defs. Tools with no arguments return ({}, []).
    """

    props = schema.get("properties", {})
    defs = schema.get("$defs", {})
    params = props.get("params")
    if not params:
        return {}, []
    if "$ref" in params:
        ref = params["$ref"].split("/")[-1]
        model = defs.get(ref, {})
    else:
        model = params
    return model.get("properties", {}), model.get("required", [])


def _type_str(field: dict) -> str:
    if "type" in field:
        return field["type"]
    if "anyOf" in field:
        # Use '/' (not '|') so the value never breaks the Markdown table.
        return " / ".join(t.get("type", "?") for t in field["anyOf"] if "type" in t) or "any"
    if "enum" in field:
        return "enum(" + ", ".join(map(str, field["enum"])) + ")"
    if "allOf" in field or "$ref" in field:
        return "object"
    return "any"


async def collect() -> list[dict]:
    tools = await mcp.list_tools()
    out = []
    for t in sorted(tools, key=lambda x: x.name):
        schema = t.inputSchema or {}
        props, required = _resolve_params(schema)
        args = []
        for arg_name, field in props.items():
            args.append(
                {
                    "name": arg_name,
                    "type": _type_str(field),
                    "required": arg_name in required,
                    "default": field.get("default"),
                    "description": field.get("description", ""),
                    "enum": field.get("enum"),
                }
            )
        # First sentence of the docstring is the summary.
        desc = (t.description or "").strip()
        summary = desc.split("\n", 1)[0].strip()
        out.append({"name": t.name, "summary": summary, "description": desc, "arguments": args})
    return out


def render_markdown(tools: list[dict]) -> str:
    lines = [
        "# maltego-mcp — Tool Reference",
        "",
        "Auto-generated by `scripts/gen_tools_doc.py` from the live MCP tool schemas. "
        f"**{len(tools)} tools.**",
        "",
        "Every tool takes its arguments inside a single `params` object. Arguments marked "
        "**required** must be supplied; others have defaults.",
        "",
    ]
    for t in tools:
        lines.append(f"## `{t['name']}`")
        lines.append("")
        lines.append(t["summary"] or "(no description)")
        lines.append("")
        if t["arguments"]:
            lines.append("| Argument | Type | Required | Default | Description |")
            lines.append("|----------|------|----------|---------|-------------|")
            for a in t["arguments"]:
                default = "" if a["default"] is None else f"`{a['default']}`"
                req = "yes" if a["required"] else "no"
                d = a["description"].replace("|", "\\|")
                typ = a["type"]
                if a.get("enum"):
                    typ += " — " + ", ".join(f"`{e}`" for e in a["enum"])
                lines.append(f"| `{a['name']}` | {typ} | {req} | {default} | {d} |")
        else:
            lines.append("_No arguments._")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    tools = asyncio.run(collect())
    root = os.path.join(os.path.dirname(__file__), "..")
    with open(os.path.join(root, "TOOLS.md"), "w", encoding="utf-8") as fh:
        fh.write(render_markdown(tools))
    with open(os.path.join(root, "tools.json"), "w", encoding="utf-8") as fh:
        json.dump({"tool_count": len(tools), "tools": tools}, fh, indent=2, ensure_ascii=False)
    print(f"Wrote TOOLS.md and tools.json ({len(tools)} tools).")


if __name__ == "__main__":
    main()
